---
- hosts: all
  vars:

  tasks:
  - name: Configure PALANTIR_ENVIRONMENT variable
    lineinfile: dest=/home/vagrant/.profile state=present line='export PALANTIR_ENVIRONMENT="vagrant"'
    tags: common

  - name: Copy gitignore
    copy: src=templates/gitignore dest=/home/vagrant/.gitignore
    tags: common

  - name: Configure global gitignore
    git_config:
      name: core.excludesfile
      scope: global
      value: /home/vagrant/.gitignore
    tags: common

  - name: Check for user-specific provisioning script
    stat: path=/var/www/{{ hostname }}/conf/vagrant/scripts/provision-user
    register: provision_user

  - name: Run user-specific provisioning.
    command: /var/www/{{ hostname }}/conf/provision-user
    when: provision_user.stat.exists
    tags: common

  - name: Add the project's vendor/bin to the path
    lineinfile: dest=/home/vagrant/.profile state=present line='export PATH="$PATH:/var/www/{{ hostname }}/vendor/bin"'
    tags: common

  - name: Change directory into the project root on login
    lineinfile: dest=/home/vagrant/.profile state=present line='cd /var/www/{{ hostname }}'
    tags: common
