---
- name: Install Apache vhost
  sudo: yes
  template: src=drupal8-skeleton.conf dest=/etc/apache2/sites-available/{{ hostname }}.conf
  tags: apache

- name: Stat {{ hostname }} vhost conf
  stat: path=/etc/apache2/sites-enabled/{{ hostname }}.conf
  register: drupal8_vhost_exists
  tags: apache

- name: Enable {{ hostname }} vhost
  sudo: yes
  shell: /usr/sbin/a2ensite {{ hostname }}
  when: drupal8_vhost_exists.stat.exists == False
  tags: apache

- name: Restart Apache
  sudo: yes
  service: name=apache2 state=restarted
  tags: apache
