---

- name: PHP | Get the installed PHP version
  command: php -r 'preg_match("/[0-9]+\.[0-9]/", phpversion(), $matches); echo current($matches);'
  register: php_version

- name: PHP | Adjust php.ini memory_limit
  become: true
  lineinfile: dest={{ item.file }}
              regexp='memory_limit'
              line='memory_limit = {{ item.value }}'
  with_items:
    - { file: "/etc/php/{{ php_version.stdout }}/apache2/php.ini", value: "{{ php_ini_memory_limit }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/fpm/php.ini", value: "{{ php_ini_memory_limit }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/cli/php.ini", value: '-1' }
  tags: PHP

- name: PHP | Enable PHP error display
  become: true
  lineinfile: dest={{ item.file }}
              regexp='^{{ item.key }}'
              line='{{ item.key }} = {{ item.value }}'
  with_items:
    - { file: "/etc/php/{{ php_version.stdout }}/apache2/php.ini", key: 'error_reporting', value: "{{ php_ini_error_reporting }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/apache2/php.ini", key: 'display_errors', value: "{{ php_ini_display_errors }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/fpm/php.ini", key: 'error_reporting', value: "{{ php_ini_error_reporting }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/fpm/php.ini", key: 'display_errors', value: "{{ php_ini_display_errors }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/cli/php.ini", key: 'error_reporting', value: "{{ php_ini_error_reporting }}" }
    - { file: "/etc/php/{{ php_version.stdout }}/cli/php.ini", key: 'display_errors', value: "{{ php_ini_display_errors }}" }
  tags: PHP

- name: PHP | Adjust php.ini upload_max_filesize
  become: true
  lineinfile: dest={{ item }}
              regexp='^upload_max_filesize'
              line='upload_max_filesize = {{ php_ini_upload_max_filesize }}'
  with_items:
    - "/etc/php/{{ php_version.stdout }}/apache2/php.ini"
    - "/etc/php/{{ php_version.stdout }}/fpm/php.ini"
    - "/etc/php/{{ php_version.stdout }}/cli/php.ini"
  tags: PHP
